### ISSUE TITLE
Christine Belzie RSOD proposal 

### ISSUE THREAD

**Issue by CBID2** [rocky-linux/documentation#2161]
## Proposed Titles/Topics

- [X]  ~~Troubleshooting for GNOME tweaks to customize desktop environment: This guide will provide solutions for issues users face when trying to customize their desktop environment with GNOME tweaks~~ **A basic user guide on [Decoder app](https://apps.gnome.org/Decoder/) for the GNOME section** #2307 **Completed**
- [X] ~~Best Practices for using knsip to take screenshots: it'll help users learn how to effectively use this tool outside of the initial guide.~~ **A basic user guide on [Decibels app](https://apps.gnome.org/en/Decibels/) for the GNOME section** #2281 **Completed**
- [x]  ~~A troubleshooting guide on fixing issues that occur with the printers: This guide will provide solutions users can implement to fix common problems they encounter when using their Brother or HP All-in-One printers with the desktop.~~ **A basic user guide on [Valuta app](https://apps.gnome.org/en/Valuta/) for the GNOME section** #2316 **Completed**
- [x]  ~~A troubleshooting guide for Desktop Sharing via RDP~~ **A basic user guide on [File Shredder app](https://apps.gnome.org/Raider/) for the GNOME section** #2323 **Completed**
- [ ]  ~~An introduction section in the Nerd Fonts guide~~ **A basic user guide on [Screenshot app](https://apps.gnome.org/en/AudioSharing/) for the GNOME section** #2325 **Completed**

~~## Additional info about the troubleshooting guides
Since the sections on Gnome Tweaks and the printers are detailed already 
I find that putting the troubleshooting guides as their own sections would make the content less overwhelming.~~

**Comment by sspencerwire** [comment]
@CBID2 Thank you for your interest! I've got a couple of questions and a comment or two. @wsoyinka may want to chime in with a few more:
* Can you expand on your first item, and explain what you intend to do there?
* Can you do the same for the printer item (item 3)?

To comment: 
* With the `ksnip` document completed in the Desktop category, I can only see item two as an enhancement to that document, rather than a document all by itself.
* The same goes for the RDP document. Can you expand these to show why they should be considered separately?
* Would the last item be a how-to, or a FAQ?

@wsoyinka Your thoughts?

**Comment by wsoyinka** [comment]
Similar thoughts as you @sspencerwire .

I'd like to vote to approve the proposed list of topics for @CBID2 's submission.   Some of the topics/titles will need minor tweaks in the titles to make fit technical documentation/guide/how-to style.  

For example, standard FAQ format does not fit existing format here https://docs.rockylinux.org/  

So instead of "FAQ for Nerd Fonts" I would recommend "Introduction to Nerd Fonts "  Or "Nerd Fonts How-to" etc etc.

**Comment by sspencerwire** [comment]
@CBID2 Since these topics have generally been approved, you can start writing anytime. ;-)

**Comment by CBID2** [comment]
> @CBID2 Since these topics have generally been approved, you can start writing anytime. ;-)
> 
> 

Great thanks @sspencerwire! 😊

**Comment by CBID2** [comment]
> @CBID2 Since these topics have generally been approved, you can start writing anytime. ;-)
> 
> 

Hey @sspencerwire. Sorry for the long pause. Haven’t been feeling too well for the past couple of weeks, so I'm just now looking at my proposal again. Are developers the main audience of Rocky Linux?

**Comment by sspencerwire** [comment]
> > @CBID2 Since these topics have generally been approved, you can start writing anytime. ;-)
> 
> Hey @sspencerwire. Sorry for the long pause. Haven’t been feeling too well for the past couple of weeks, so I'm just now looking at my proposal again. Are developers the main audience of Rocky Linux?

Hi @CBID2, I'm sorry you haven't been feeling well lately. While the Rocky project as a whole is probably more focused towards enterprise users, that isn't our push for RSOD. We have a Desktop special interest group, which is focused on user-based documents and gaming. RSOD aims to put some desktop content on our documentation site to help end-users get the most out of the desktop. Your documents can be enterprise or end-user based, and they will still fit. z

We are to this point in the RSOD process:

July 1 - August 30: Content creation and translations 

I hope you are feeling better!

**Comment by CBID2** [comment]
> @CBID2 You still have time to complete content for this, if you are interested. 

I am @sspencerwire. Just struggling with getting started due to my lack firsthand experience with the product. Also, how will participants receive the $200($1000) reward? I don't see it mentioned in the RSOD page.

**Comment by sspencerwire** [comment]
> > @CBID2 You still have time to complete content for this, if you are interested.
> 
> I am @sspencerwire. Just struggling with getting started due to my lack firsthand experience with the product. Also, how will participants receive the $200($1000) reward? I don't see it mentioned in the RSOD page.

We are working on the logistics now, BUT, I **CAN** tell you that the project has been fully funded.

**Comment by CBID2** [comment]
Hi @sspencerwire. I did my PR for the fifth bullet point(I'm going to do each bullet point as separate PRs to make it easier for you and the other maintainers to review and merge them.) It's #2249.

**Comment by wsoyinka** [comment]
Hello @CBID2 :

Thank you for #2249  :-)

Upon reviewing that PR #2249 and cross matching it with your stated issue #2161 proposing your contributions for RSOD 2024, it looks like your stated intention ["An introduction section in the Nerd Fonts guide] was to enhance an existing docs.rockylinux.org guide/book/content.  

As much as we always welcome and encourage, improvements and enhancements to existing docs.r.o content, this is not the intent/focus of RSOD 2024.  

Participants in RSOD 2024 have to contribute brand new content to populate the new "Desktop" category.   Amongst other things, this means that each participant will have to be listed and noted as the primary "Author" of their contributions. 

The organizers of RSOD 2024 missed pointing out this important gap in your issue #2161. 

Please do your best to ensure that your remaining contributions/submissions for RSOD 2024 are brand new documents/guides/content originally authored by you. 

Please let us know if you have any additional questions.

**Comment by CBID2** [comment]
> Hello @CBID2 :
> 
> 
> 
> Thank you for #2249  :-)
> 
> 
> 
> Upon reviewing that PR #2249 and cross matching it with your stated issue #2161 proposing your contributions for RSOD 2024, it looks like your stated intention ["An introduction section in the Nerd Fonts guide] was to enhance an existing docs.rockylinux.org guide/book/content.  
> 
> 
> 
> As much as we always welcome and encourage, improvements and enhancements to existing docs.r.o content, this is not the intent/focus of RSOD 2024.  
> 
> 
> 
> Participants in RSOD 2024 have to contribute brand new content to populate the new "Desktop" category.   Amongst other things, this means that each participant will have to be listed and noted as the primary "Author" of their contributions. 
> 
> 
> 
> The organizers of RSOD 2024 missed pointing out this important gap in your issue #2161. 
> 
> 
> 
> Please do your best to ensure that your remaining contributions/submissions for RSOD 2024 are brand new documents/guides/content originally authored by you. 
> 
> 
> 
> Please let us know if you have any additional questions. 
> 
> 

Hi @wsoyinka. My original plan for the fifth bullet point was to create an FAQ guide for Nerd Fonts but it was apparently not suited for the section. Sorry for the mistake.

**Comment by wsoyinka** [comment]
Understood and no worries @CBID2  :-) !

FAQ style content won't work either.  All the new RSOD 2024 contributions need to seamlessly  fit under :

https://docs.rockylinux.org/desktop/

i.e.

https://github.com/rocky-linux/documentation/tree/main/docs/desktop

**Comment by wsoyinka** [comment]
Hey @CBID2   - I am personally not familiar with that [GNOME audio sharing tool.](https://flathub.org/apps/de.haeckerfelix.AudioSharing)  

But my quick read through makes me feel like it certainly fits the Desktop category and thus a good fit !  

At a minimum for RSOD purposes, you'll need to contribute 5 separate guides/how-tos/tutorials detailing how to use that tool  to accomplish some stated objective(s).  

So you've identified 1 new  original topic. You need 4 more . Thank you !

**Comment by CBID2** [comment]
> Hey @CBID2 - I am personally not familiar with that [GNOME audio sharing tool.](https://flathub.org/apps/de.haeckerfelix.AudioSharing)
> 
> But my quick read through makes me feel like it certainly fits the Desktop category and thus a good fit !
> 
> At a minimum for RSOD purposes, you'll need to contribute 5 separate guides/how-tos/tutorials detailing how to use that tool to accomplish some stated objective(s).
> 
> So you've identified 1 new original topic. You need 4 more . Thank you !
Hi @wsoyinka! I did the user guide on the audio sharing tool that I mentioned. It's PR #2281

**Comment by wsoyinka** [comment]
@CBID2  - Looking.....  👀  👀  👀 

I will not recommend that you try writing guides/how-tos/tutorials/docs for others about any of these apps without you running and testing the apps yourself in your own environment. 
I could be wrong, but your POVE  (Point of View and Experience) is very very important/valuable for documenting things like this.

**Comment by CBID2** [comment]
> @CBID2  - Looking.....  👀  👀  👀 
> 
> 
> 
> I will not recommend that you try writing guides/how-tos/tutorials/docs for others about any of these apps without you running and testing the apps yourself in your own environment. 
> 
> I could be wrong, but your POVE  (Point of View and Experience) is very very important/valuable for documenting things like this. 

Thanks for your honesty @wsoyinka. I’m going to try and see how much storage I can remove to make Virtualbox work.

**Comment by CBID2** [comment]
> @CBID2  - Looking.....  👀  👀  👀 
> 
> 
> 
> I will not recommend that you try writing guides/how-tos/tutorials/docs for others about any of these apps without you running and testing the apps yourself in your own environment. 
> 
> I could be wrong, but your POVE  (Point of View and Experience) is very very important/valuable for documenting things like this. 

Hi @wsoyinka. Here is what I tried so far
 - Downloading VirtualBox to my Mac: received an error message that it doesn't support my CPU’s architecture 
- Downloaded a free trial to Parallels Desktop, started Windows, and tried setting up VirtualBox there. Encountered an unknown error while trying to install it. 

Given that the RSOD initiative ends soon, would it be ok if I write user guides that follow  
the same style as the one I did for the Audio Sharing app?

**Comment by wsoyinka** [comment]
@CBID2  - 

Regarding the VirtualBox error, it sounds like your Mac uses an ARM architecture.  If that is the case I will instead highly recommend this alternative application instead -  

- https://mac.getutm.app

**Comment by CBID2** [comment]
> @CBID2  - 
> 
> 
> 
> Regarding the VirtualBox error, it sounds like your Mac uses an ARM architecture.  If that is the case I will instead highly recommend this alternative application instead -  
> 
> 
> 
> - https://mac.getutm.app
> 
> 
> 
> 
> 
> 
> 
> 

Hi @wsoyinka. I made an update to my PR. Can you review (and possibly merge it) please? The deadline is coming soon and I want to get started on my  other four contributions before it's too late.

**Comment by wsoyinka** [comment]
@CBID2  - Hi :-)

Do you now have a system/VM that runs Rocky Linux (or similar) to test the procedures and applications that you are writing about for RSOD 2024 ?

**Comment by CBID2** [comment]
> @CBID2  - Hi :-)
> 
> 
> 
> Do you now have a system/VM that runs Rocky Linux (or similar) to test the procedures and applications that you are writing about for RSOD 2024 ?

Hey @wsoyinka. I do actually! :) I mentioned this in my latest comment in my PR :)

**Comment by CBID2** [comment]
I'm officially done! Thank you @sspencerwire

**Comment by sspencerwire** [comment]
@CBID2 Thank you for participating in RSOD. This issue is being closed.

**Comment by CBID2** [comment]
> @CBID2 Thank you for participating in RSOD. This issue is being closed. 

You’re welcome @sspencerwire.
